POST  http://localhost:5115/meals
Content-Type: application/json

{
    "name": "BIg beef",
    "descriptions": "mia loves it!",
    "startDateTime": "2022-08-17",
    "endDateTime": "2022-08-17",
    "savory": [
        "Beef",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "wow"
    ]
}

###

GET https://localhost:7197/miameals/fa88a92f-599e-44b4-a301-1f074ad6a81c